#ifndef HSSH_VERSION_H
#define HSSH_VERSION_H

#define HSSH_VERSION_MAJOR 0
#define HSSH_VERSION_MINOR 2
#define HSSH_VERSION_PATCH 0

#define HSSH_VERSION_STRING "0.2.0-preview"

#endif // HSSH_VERSION_H
